### ISSUE TITLE
Cannot scroll to view all

### ISSUE THREAD

**Issue by xuanzi23** [dkhamsing/ScrollTab#15]
I have problem after I initialise. Why cannot scroll to the end of the list?
![screen shot 2016-12-29 at 5 34 48 pm](https://cloud.githubusercontent.com/assets/19340910/21540834/2af52aee-cded-11e6-8288-7406bbe2d571.png)

**Comment by dkhamsing** [comment]
Does it have to do with your frame values
Can you try changing them

**Comment by xuanzi23** [comment]
@dkhamsing u means change back the size of the frame 
FROM 
dkController.view.frame = CGRectMake(0, 58, 500, 60)
TO
tabController.view.frame = CGRectMake(0, 20, 320, 40)?

**Comment by dkhamsing** [comment]
Sure
Except leave the 58 value

**Comment by xuanzi23** [comment]
If I change to tabController.view.frame = CGRectMake(0, 20, 320, 40),
that wont fix all the screen size.

I make some changes for that
let screenSize: CGRect = UIScreen.mainScreen().bounds
tabController.view.frame = CGRectMake(0, 58, screenSize.width , 60)

So I think can fix all the phone size

**Comment by dkhamsing** [comment]
Well we were just trying to figure out your issue

Did changing the width fix it ?

**Comment by xuanzi23** [comment]
I think so, maybe need test more phone size first

**Comment by dkhamsing** [comment]
Pk

**Comment by dkhamsing** [comment]
Feel free to be open if you have any questions
