### ISSUE TITLE
Possible to add new feature?

### ISSUE THREAD

**Issue by vincia1215** [dkhamsing/ScrollTab#16]
It is possible to add userInteractionEnabled in button of  DKScrollingTab ?

**Comment by dkhamsing** [comment]
it's off because the interaction is supposed to be from the collection view (did select)
does that not work for you?

feel free to copy the source and change manually

**Comment by vincia1215** [comment]
Thanks for reply.I just manage to do that by force the tab stay on current
selected tab in some specific condition

**Comment by dkhamsing** [comment]
Ok
